import { useEffect, useRef, useState } from 'react';
import type { ItDecision, ItHome, ItWorkspace } from '@learnsprint/contracts';
import { api } from '../api';
import CareerPaths from './CareerPaths';
import './career.css';
import './it-support.css';

const ticketLabels:Record<string,string>={vpn:'Remote access',access:'CRM access',print:'Dispatch labels',queue:'Team workload'};
export default function ItSupport(){
  const [home,setHome]=useState<ItHome|null>(null),[work,setWork]=useState<ItWorkspace|null>(null);
  const [draft,setDraft]=useState<Record<string,Partial<ItDecision>>>({}),[note,setNote]=useState('');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false);
  const lock=useRef(false),pending=useRef<{path:string;body:Record<string,unknown>}|null>(null);
  const [selectedTicket,setSelectedTicket]=useState('vpn');
  const s=work?.shift;
  const dirty=!!s&&JSON.stringify(draft)!==JSON.stringify(s.decisions);
  const closed=s?.phase==='handed_off';
  const incomplete=Object.values(draft).some(d=>!d.priority||!d.assignee||!d.action);
  const evidenceCount=work?.tickets.filter(t=>!!t.evidence).length??0;
  const decisionCount=work?.tickets.filter(t=>draft[t.id]?.priority&&draft[t.id]?.assignee&&draft[t.id]?.action).length??0;
  const nextStep=closed?'Your handoff is saved. Download it or try changed conditions.':incomplete?'Complete all three choices on each ticket you started.':dirty?'Save your ticket choices before continuing.':evidenceCount<3?'Open the current impact and workaround evidence for each ticket.':decisionCount<3?'Choose priority, responsible team and next action for every ticket.':!s?.review?'Review your saved decisions against the current facts.':s.phase==='triage'?'Advance the shift to discover the incident.':'Review any remaining issues, then prepare your handoff.';

  function accept(w:ItWorkspace){setWork(w);setDraft(w.shift.decisions);history.replaceState({},'',`/career?role=it-support&itShift=${w.shift.id}`);setConfirm(false);}
  async function load(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{
    const h=await api<ItHome>('/career/it/home');setHome(h);
    const id=new URLSearchParams(location.search).get('itShift');
    if(id)accept(await api<ItWorkspace>(`/career/it/sessions/${encodeURIComponent(id)}`));
  }catch(e){setError(e instanceof Error?e.message:'Cannot open the service desk.');}finally{lock.current=false;setBusy(false);}}
  useEffect(()=>{document.title='IT Support — LearnSprint';void load();},[]);
  useEffect(()=>{if(!dirty&&!note&&!busy)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,note,busy]);
  async function send(path:string,body:Record<string,unknown>,retry=false){if(lock.current)return;lock.current=true;setBusy(true);setError('');
    const req=retry&&pending.current?pending.current:{path,body:{...body,requestId:crypto.randomUUID()}};pending.current=req;
    try{accept(await api<ItWorkspace>(req.path,req.body));pending.current=null;if(req.body.type==='handoff')setNote('');}
    catch(e){setError(e instanceof Error?e.message:'The action could not be saved.');}
    finally{lock.current=false;setBusy(false);}}
  const action=(type:string,extra:Record<string,unknown>={})=>s&&send(`/career/it/sessions/${s.id}/commands`,{type,expectedRevision:s.revision,...extra});
  function edit(id:string,key:keyof ItDecision,value:string){setConfirm(false);setDraft(d=>({...d,[id]:{...(d[id]??{}),[key]:value} as Partial<ItDecision>}));}
  function exportReport(){if(!s?.handoff)return;const blob=new Blob([JSON.stringify({scenario:'it-support',version:s.version,variant:s.variant,handoff:s.handoff,sourceHandoff:work?.sourceHandoff,history:s.history},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='learnsprint-it-handoff.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <div className="career-app it-app"><a className="cr-skip" href="#it-main">Skip to service desk</a><header className="it-header"><a href="/career">LearnSprint</a><span>THE CAREER PRACTICE DESK</span></header><main id="it-main" className="it-main">
    <CareerPaths compact={!!s}/>
    <section className={`it-intro ${s?'it-intro-working':''}`}><p className="it-eyebrow">IT SUPPORT / INCIDENT COORDINATOR</p><h1>{s?'Your service desk.':<>Read the signal.<br/>Own the next step.</>}</h1><p>Three tickets. Limited specialist time. A service disruption that changes what matters. Investigate, route and leave a handoff someone can act on.</p><p className="it-caption">Fictional practice · Authored evidence and policy checks · No live IT systems or AI inference in this role</p></section>
    {error&&<div role="alert" className="it-error"><p>{error}</p>{pending.current&&<button disabled={busy} onClick={()=>void send('',{},true)}>Retry the same action</button>}<button disabled={busy} onClick={()=>{if(!dirty||window.confirm('Discard unsaved ticket choices and reopen the saved shift?')){pending.current=null;void load();}}}>Reopen saved shift</button></div>}
    <p role="status" aria-live="polite">{busy?'Saving / opening your desk…':s?.history.at(-1)?.message??''}</p>
    {!s?<><button className="it-primary" disabled={busy||!home} onClick={()=>void send('/career/it/sessions',{})}>Start my IT shift ↗</button><section className="it-saved"><h2>Your saved IT shifts</h2>{home?.sessions.length?home.sessions.map(x=><a key={x.id} href={`/career?role=it-support&itShift=${x.id}`}>{x.variant==='replay'?'Changed-condition replay':'First service desk shift'} · {x.phase.replace('_',' ')} · {new Date(x.createdAt).toLocaleDateString()}</a>):<p>No saved IT shifts yet. Your browser keeps access to the shifts you create.</p>}</section></>:<>
      <ol className="it-steps" aria-label="Shift stages">{(['triage','incident','handed_off'] as const).map((phase,i)=><li key={phase} aria-current={s.phase===phase?'step':undefined}><span>{i+1}</span>{['Investigate & triage','Respond to change','Handoff saved'][i]}</li>)}</ol><aside className="it-progress" aria-label="Your next step"><strong>Next step</strong><p>{nextStep}</p><span>{evidenceCount}/3 current sources opened · {decisionCount}/3 complete ticket decisions</span></aside><div className="it-stage"><strong>{s.variant==='replay'?'Changed conditions':'First shift'} · {s.phase==='triage'?'09:00 / Triage':s.phase==='incident'?'09:20 / Respond':'Handoff saved'}</strong><span>v{s.version} · facts {s.world} · revision {s.revision}</span></div>
      {s.phase==='incident'&&<aside className="it-incident"><strong>NEW INCIDENT / 09:20</strong><p>{s.variant==='first'?'VPN impact widened and the browser workaround failed. Open the current source records before reprioritizing.':'The CRM request is now needed today. Identity verification has completed. Recheck the source records.'}</p></aside>}
      <details className="it-policy" open><summary>Team policy & available capacity</summary><p><strong>P1 / page incident owner:</strong> a critical shared service is blocked with no workable alternative. <strong>P2 / respond this shift:</strong> business work is affected today but a workaround exists. <strong>P3 / scheduled queue:</strong> isolated low impact or future need.</p><p>Network: 2 effort units. Identity: 1. Service desk: 2. Effort is a scenario estimate, not elapsed time. Network owns VPN/shared services; identity owns account grants; service desk owns workstation issues. Never request passwords or bypass MFA. If demand exceeds capacity, escalate and record the queue risk; do not pretend escalation fixes it.</p></details>
      <div className="it-desk"><nav className="it-queue" aria-label="Ticket queue"><p className="it-eyebrow">TICKET QUEUE / {work!.tickets.length}</p>{work!.tickets.map(t=><button key={t.id} aria-pressed={selectedTicket===t.id} aria-controls={`ticket-${t.id}`} onClick={()=>setSelectedTicket(t.id)}><strong>{t.title}</strong><small>{t.requester}</small><span>{draft[t.id]?.priority?.toUpperCase()??'Not prioritized'} · {t.evidence?'Source opened':'Source unread'}</span></button>)}</nav><div className="it-tickets">{work!.tickets.map(t=><article key={t.id} id={`ticket-${t.id}`} hidden={selectedTicket!==t.id} className="it-ticket"><div className="it-ticket-head"><span>{t.id.toUpperCase()} / {t.effort} effort</span><span>{t.requester}</span></div><h2>{t.title}</h2><p>{t.summary}</p><button disabled={busy||closed||dirty||!!pending.current} onClick={()=>void action('read',{ticketId:t.id})}>{t.evidence?'Refresh source record':'Ask for impact & workaround'}</button>{t.evidence?<blockquote>{t.evidence}<cite>{t.source} · facts {s.world}</cite></blockquote>:<p className="it-caption">Current evidence not opened. {s.world===2?'Earlier source records are historical.':''}</p>}
      <fieldset disabled={busy||closed||!!pending.current}><legend>Triage decision</legend><label>Priority<select value={draft[t.id]?.priority??''} onChange={e=>edit(t.id,'priority',e.target.value)}><option value="" disabled>Choose priority</option><option value="p1">P1 · Critical incident</option><option value="p2">P2 · This shift</option><option value="p3">P3 · Scheduled queue</option></select></label><label>Responsible team<select value={draft[t.id]?.assignee??''} onChange={e=>edit(t.id,'assignee',e.target.value)}><option value="" disabled>Choose team</option><option value="service-desk">Service desk</option><option value="network">Network</option><option value="identity">Identity</option></select></label><label>Next action<select value={draft[t.id]?.action??''} onChange={e=>edit(t.id,'action',e.target.value)}><option value="" disabled>Choose action</option><option value="investigate">Verify / investigate</option><option value="workaround">Use approved workaround</option><option value="escalate">Page incident owner</option></select></label></fieldset></article>)}</div><aside className="it-desk-context"><p className="it-eyebrow">AVAILABLE CAPACITY</p><dl><div><dt>Network</dt><dd>2 units</dd></div><div><dt>Identity</dt><dd>1 unit</dd></div><div><dt>Service desk</dt><dd>2 units</dd></div></dl><h3>Before you commit</h3><p>Check the impact and workaround. Route the ticket to the team that owns the service.</p><p>Escalation records urgency; it does not create extra capacity.</p>{s.review&&<a href="#it-review">Jump to review ↓</a>}</aside></div>
      {!closed&&<div className="it-actions"><button disabled={busy||!dirty||incomplete||!!pending.current} onClick={()=>void action('save',{decisions:draft})}>Save triage</button><button disabled={busy||dirty||!!pending.current} onClick={()=>void action('review')}>Review decisions</button>{dirty&&<button disabled={busy||!!pending.current} onClick={()=>{setDraft(s.decisions);setConfirm(false);}}>Discard unsaved choices</button>}{dirty&&<span>Unsaved choices — complete each started ticket, then save.</span>}</div>}
      {s.review&&<section id="it-review" className="it-review" tabIndex={-1}><p className="it-eyebrow">REVIEW / FACTS {s.review.world}</p><h2>{s.review.issues.length?'What still needs attention':'Your response fits the recorded facts'}</h2><p>{Object.entries(s.review.workload).map(([k,v])=>`${k}: ${v} effort`).join(' · ')}</p>{s.review.issues.length?<ul>{s.review.issues.map((x,i)=><li key={i}><strong>{ticketLabels[x.ticketId]}:</strong> {x.message}</li>)}</ul>:<p>Priorities, owners and actions match this fictional team policy. This does not establish professional competence.</p>}{dirty&&<p>This review describes the saved decisions; you have unsaved changes.</p>}</section>}
      {!closed&&s.phase==='triage'&&<button className="it-primary" disabled={busy||dirty||!s.review||!!pending.current} onClick={()=>void action('incident')}>Start the shift — see what changes ↗</button>}
      {!closed&&s.phase==='incident'&&<section className="it-handoff"><h2>Leave a useful handoff.</h2><p>State the impact, who owns the next step and any unresolved queue risk. This is a work artifact, not an essay for an AI grade.</p><button disabled={busy||!!pending.current||!!note} onClick={()=>setNote("Current impact: \nResponsible teams and next steps: \nWorkaround or escalation: \nUnresolved risks and next check: ")}>Use a handoff outline</button><label>Handoff note (20–1500 characters)<textarea value={note} maxLength={1500} disabled={busy||!!pending.current} onChange={e=>{setNote(e.target.value);setConfirm(false);}}/></label><button disabled={busy||dirty||!s.review||note.trim().length<20||!!pending.current} onClick={()=>setConfirm(true)}>Preview handoff</button>{confirm&&<div className="it-confirm"><h3>Save this exact handoff?</h3><p>{note}</p><p>{s.review?.issues.length} unresolved observations will remain in the report. This makes the shift read-only; no real tickets are changed.</p><button disabled={busy} onClick={()=>void action('handoff',{note})}>Save final handoff</button><button disabled={busy} onClick={()=>setConfirm(false)}>Keep working</button></div>}</section>}
      {s.handoff&&<section className="it-handoff"><p className="it-eyebrow">SAVED HANDOFF</p><h2>A record of your decisions.</h2><p className="it-note">{s.handoff.note}</p><div className="it-report-grid">{Object.entries(s.handoff.decisions).map(([id,d])=><article key={id}><h3>{ticketLabels[id]}</h3><p>{d.priority.toUpperCase()} · {d.assignee}</p><p>{d.action==='workaround'?'Use approved workaround':d.action==='escalate'?'Page incident owner':'Verify / investigate'}</p></article>)}</div><p>{s.handoff.review.issues.length} unresolved observations retained. No learning score or certification.</p><div className="it-actions"><button onClick={exportReport}>Download handoff JSON</button>{s.variant==='first'&&<button disabled={busy||!!pending.current} onClick={()=>void send('/career/it/sessions',{sourceId:s.id})}>Try changed conditions ↗</button>}</div></section>}
      {s.handoff&&work?.sourceHandoff&&<section className="it-comparison"><p className="it-eyebrow">FIRST SHIFT / CHANGED CONDITIONS</p><h2>What changed in your response?</h2><p>These shifts have different facts. Compare your decisions, not a score. Fewer observations alone do not prove learning.</p><div className="it-comparison-scroll"><table><caption>Frozen decisions from both handoffs</caption><thead><tr><th scope="col">Ticket</th><th scope="col">First shift</th><th scope="col">Changed conditions</th></tr></thead><tbody>{work.tickets.map(t=>{const before=work.sourceHandoff!.decisions[t.id],after=s.handoff!.decisions[t.id];const label=(d:ItDecision|undefined)=>d?`${d.priority.toUpperCase()} · ${d.assignee} · ${d.action}`:'No decision recorded';return <tr key={t.id}><th scope="row">{ticketLabels[t.id]}</th><td>{label(before)}</td><td>{label(after)}</td></tr>;})}<tr><th scope="row">Unresolved observations</th><td>{work.sourceHandoff.review.issues.length}</td><td>{s.handoff.review.issues.length}</td></tr></tbody></table></div><details><summary>Read your earlier handoff</summary><p className="it-note">{work.sourceHandoff.note}</p></details><p>Try explaining which new fact changed your priority, owner or next action. Use both source records when discussing your choices.</p></section>}
      <details className="it-history"><summary>Decision history ({s.history.length})</summary><ol>{s.history.map((h,i)=><li key={i}><time dateTime={h.at}>{new Date(h.at).toLocaleTimeString()}</time> {h.message}</li>)}</ol></details>
      <p className="it-caption">Saved on the demo server · owned by this browser · scenario 1.0.0 · content awaits practitioner review</p>
    </>}
  </main></div>;
}
