import type { CareerAssistanceSnapshot, CareerEvaluation, CareerWorkspace } from '@learnsprint/contracts';
import { shiftTime } from './api';
import './report.css';

export function assistanceLabel(value: CareerAssistanceSnapshot | null): string {
  if (!value || value.history === 'unknown-before-tracking') return 'Earlier help unknown';
  if (value.mode === 'independent') return 'No in-app guidance requested';
  if (value.mode === 'assisted') return 'Completed with recorded help';
  return 'Guided practice';
}

export default function LearningReport({ work, blocked, onReplay }: { work: CareerWorkspace; blocked: boolean; onReplay(): void }) {
  const report = work.report;
  if (!report) return null;
  const { brief, final, baseline, previous, assistance } = report;
  const changedWorld = !!baseline && baseline.worldRevision !== final.worldRevision;
  function download(): void {
    const blob = new Blob([JSON.stringify(report, null, 2) + '\n'], { type: 'application/json' });
    const url = URL.createObjectURL(blob), link = document.createElement('a');
    link.href = url; link.download = `learnsprint-shift-${report!.sessionId}.json`;
    document.body.append(link); link.click(); link.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <section className="cr-learning-report" id="cr-learning-report" aria-labelledby="cr-report-title">
    <header className="cr-report-header"><div><p className="cr-eyebrow">YOUR WORK / SAVED EVIDENCE</p><h2 id="cr-report-title" tabIndex={-1}>A shift worth looking back on.</h2><p>{brief.title} · {assistanceLabel(assistance)}</p></div><button onClick={download}>Download my record <span aria-hidden="true">↓</span></button></header>
    <div className="cr-report-summary"><div className="cr-report-number"><strong>{final.outcome.issues.length.toString().padStart(2, '0')}</strong><span>unresolved observations<br/>at handoff</span></div><div><h3>{final.outcome.feasible ? 'The final plan fits the recorded conditions.' : 'The handoff is saved. Some work is still unresolved.'}</h3><p>{final.outcome.dependsOnExpectedStock ? 'This projection still relies on expected stock arriving on time.' : 'The used departures do not rely on replenishment.'} No goods were actually dispatched.</p><p className="cr-small">Saved <time dateTime={report.finalizedAt}>{new Date(report.finalizedAt).toLocaleString('en')}</time> · review {final.number} · plan {final.artifactRevision} · facts {final.worldRevision}</p></div></div>
    <div className="cr-report-checks">{checks(final).map(([label, met]) => <div key={label} className={met ? '' : 'needs-attention'}><span aria-hidden="true">{met ? '✓' : '!'}</span><strong>{label}</strong><small>{met ? 'Met in projection' : 'Unresolved'}</small></div>)}</div>
    {final.outcome.issues.length ? <section className="cr-report-unresolved"><h3>For the next shift</h3><ul>{final.outcome.issues.map((issue, i) => <li key={i}>{issue.message}</li>)}</ul><p className="cr-small">Recorded observations from review {final.number}; completing a handoff does not resolve them.</p></section> : null}
    <div className="cr-report-columns"><section><p className="cr-eyebrow">THE DECISIONS</p><h3>From the first recorded plan to handoff</h3>{baseline ? <><div className="cr-report-compare"><ReviewSummary title="First recorded" review={baseline}/><span aria-hidden="true">→</span><ReviewSummary title="Final handoff" review={final}/></div><p>{changedWorld ? 'The two reviews used different facts. An earlier plan is shown as it was evaluated at the time.' : 'Both recorded plans used the same world revision.'}</p><p className="cr-small">Replenishment ETA: {shiftTime(baseline.eta)} → {shiftTime(final.eta)}. {baseline.agreement?.agreementId === final.agreement?.agreementId ? 'Recorded customer terms unchanged.' : 'A different customer agreement is included at handoff.'}</p><p className="cr-small">{baseline.id === final.id ? 'Only one reviewed plan was recorded. There is no separate before-and-after result.' : `${report.changes.length} allocation cells changed between these recorded plans.`}</p>{report.changes.length ? <ul className="cr-report-changes">{report.changes.map(c => <li key={`${c.orderId}-${c.departureId}`}><span>Order {c.orderId.toUpperCase()} · {brief.departures.find(d => d.id === c.departureId)?.name}</span><strong>{c.before} → {c.after} kits</strong></li>)}</ul> : null}</> : <p>No earlier recorded plan is available for comparison.</p>}</section><section><p className="cr-eyebrow">THE CONDITIONS</p><h3>What the final plan depends on</h3><dl className="cr-report-facts"><div><dt>Confirmed stock</dt><dd>{brief.onHand} kits</dd></div><div><dt>Expected replenishment</dt><dd>{brief.replenishmentQuantity} kits · {shiftTime(final.eta)}</dd></div><div><dt>Shipping</dt><dd>{final.outcome.cost} / {final.outcome.budget} units</dd></div><div><dt>Customer B</dt><dd>{final.agreement ? 'Changed terms recorded' : 'Original promise applies'}</dd></div></dl><Commitments review={final}/></section></div>
    <section className="cr-report-assistance"><div><p className="cr-eyebrow">HOW THIS ATTEMPT WAS COMPLETED</p><h3>{assistanceLabel(assistance)}</h3><p>Work questions and source facts are separate from coaching. These counts cover help recorded in LearnSprint; they cannot establish what happened outside the app.</p></div>{assistance ? <dl><div><dt>Guidance requests</dt><dd>{assistance.helpCount}</dd></div><div><dt>AI-selected focuses</dt><dd>{assistance.aiFocusCount}</dd></div><div><dt>Guided voice starts</dt><dd>{assistance.guidedVoiceCount}</dd></div></dl> : <p>Help tracking was not available for this handoff.</p>}</section>
    {previous ? <section className="cr-report-transfer"><p className="cr-eyebrow">TWO DIFFERENT SITUATIONS</p><h3>Your first shift and this replay</h3><div className="cr-report-columns"><section><a href={`/career?shift=${encodeURIComponent(previous.sessionId)}`}>{previous.title} ↗</a><ReviewSummary title={`Scenario ${previous.packVersion}`} review={previous.final}/><p className="cr-small">{previous.onHand} on hand + {previous.replenishmentQuantity} expected kits</p><p className="cr-small">{assistanceLabel(previous.assistance)}{previous.assistance ? ` · ${previous.assistance.helpCount} guidance requests` : ''}</p><Commitments review={previous.final}/></section><section><strong>{brief.title}</strong><ReviewSummary title={`Scenario ${brief.version}`} review={final}/><p className="cr-small">{brief.onHand} on hand + {brief.replenishmentQuantity} expected kits</p><p className="cr-small">{assistanceLabel(assistance)}{assistance ? ` · ${assistance.helpCount} guidance requests` : ''}</p><Commitments review={final}/></section></div><p>Stock and customer conditions changed. These are two recorded outcomes, not a measured learning gain or a job-readiness score.</p></section> : null}
    <details className="cr-details"><summary>Inspect the final allocations and recorded sources</summary><div className="cr-table-scroll" tabIndex={0} role="region" aria-label="Final allocation evidence"><table className="cr-review-table"><caption>Final saved review {final.number} · scenario {brief.version}</caption><thead><tr><th scope="col">Order</th>{brief.departures.map(d => <th scope="col" key={d.id}>{d.name}</th>)}</tr></thead><tbody>{brief.orders.map(o => <tr key={o.id}><th scope="row">{o.id.toUpperCase()} · {o.customer}</th>{brief.departures.map(d => <td key={d.id}>{final.plan[o.id][d.id]} kits</td>)}</tr>)}</tbody></table></div><ul className="cr-report-sources">{report.facts.map(r => <li key={r.id}><strong>{r.actorName} · {r.question}</strong><p>{r.message}</p><small>Facts {r.worldRevision} · {r.worldRevision === final.worldRevision ? 'Final world revision' : 'Historical world revision'} · {r.facts.map(f => `${f.sourceLabel} (${f.sourceVersion})`).join('; ')}</small></li>)}</ul>{!report.facts.length ? <p>No stakeholder questions were recorded in this attempt.</p> : null}</details>
    {report.help.length ? <details className="cr-details"><summary>Recorded learning activities ({report.help.length})</summary><ul className="cr-report-sources">{report.help.map(h => <li key={h.id}><strong>{h.focus?.activity.title ?? h.activity.title}</strong><p>{h.focus?.activity.objective ?? h.activity.objective}</p><small>Plan {h.artifactRevision} · facts {h.worldRevision} · {h.focus ? 'AI-selected activity, authored wording' : 'Authored guidance'}</small></li>)}</ul></details> : null}
    <details className="cr-details"><summary>Full decision timeline ({report.timeline.length} recorded actions)</summary><ol className="cr-report-timeline">{report.timeline.map(e => <li key={e.id}><p>{e.summary}</p><small>Plan {e.artifactRevision} · facts {e.worldRevision} · {e.origin ? e.origin.mode : 'Direct action'} · <time dateTime={e.createdAt}>{new Date(e.createdAt).toLocaleTimeString('en')}</time></small></li>)}</ol></details>
    {work.nextReplay ? <section className="cr-replay-invite"><div><p className="cr-eyebrow">TAKE THE NEXT SHIFT</p><h3>{work.nextReplay.title}</h3><p>{work.nextReplay.sessionId ? 'Your next attempt is already saved. Continue it with its original decisions and help history.' : 'A different stock balance. A customer with different needs. Start directly with the known delay and a blank board; earlier agreements do not carry over.'}</p><p className="cr-small">Fact-finding remains available. Optional guidance records this new attempt as assisted before it appears.</p></div><button className="cr-primary" disabled={blocked} onClick={onReplay}>{work.nextReplay.sessionId ? 'Continue my replay' : 'Try the new situation'} <span aria-hidden="true">→</span></button></section> : null}
    <p className="cr-report-footnote">This record describes one fictional exercise. It is not a certificate, proof of delivery or assessment of employability. Downloading saves a local JSON file; it does not share the report with anyone.</p>
  </section>;
}

function checks(review: CareerEvaluation): [string, boolean][] {
  const r = review.outcome;
  return [['Stock timing', r.inventoryMet], ['Departure capacity', r.capacityMet], ['Order quantities', r.quantitiesMet], ['Customer promises', r.commitmentsMet], ['Shipping budget', r.budgetMet]];
}
function ReviewSummary({ title, review }: { title: string; review: CareerEvaluation }) {
  return <div className="cr-report-review"><span>{title}</span><strong>{review.outcome.issues.length} unresolved</strong><p>{review.outcome.cost} shipping units</p><small>Review {review.number} · facts {review.worldRevision}</small></div>;
}
function Commitments({ review }: { review: CareerEvaluation }) {
  return <ul className="cr-report-promises">{review.outcome.orders.map(o => <li key={o.orderId}><strong>Order {o.orderId.toUpperCase()} · {o.met ? 'Projected commitment met' : 'Unresolved commitment'}</strong><p>{o.terms.map(t => `${t.scheduledBy}/${t.quantity} kits cumulatively by ${shiftTime(t.by)}`).join('; ')}</p></li>)}</ul>;
}
