import type { Dispatch } from 'react';
import { currentResult, currentSuitePassed, intervention, latestSuite, MISSIONS, samePolicy, simulate } from './preview-domain';
import type { Action, Case, MissionId, Policy, Result, SourceId, Work } from './preview-domain';

type Props = {
  missionId: MissionId; work: Work; dispatch: Dispatch<Action>;
  hintVisible: boolean; comparisonVisible: boolean;
  showHelp: (kind: 'hints' | 'comparisons') => void; closeComparison: () => void;
  openSource: (source: SourceId) => void; onNext: () => void;
};

export function Workbench({ missionId, work, dispatch, hintVisible, comparisonVisible, showHelp, closeComparison, openSource, onNext }: Props) {
  const mission = MISSIONS[missionId];
  const selected = mission.cases.find(item => item.id === work.selectedCaseId)!;
  const selectedRun = currentResult(work, selected.id);
  const result = selectedRun?.results.find(item => item.caseId === selected.id);
  const stale = !!selectedRun && !samePolicy(selectedRun.policy, work.policy);
  const suite = latestSuite(work);
  const suiteCurrent = !!suite && samePolicy(suite.policy, work.policy);
  const complete = currentSuitePassed(work);
  const coach = intervention(missionId, work);
  const suiteCount = work.runs.filter(run => run.suite).length;
  return <>
    <section className="mp-brief-strip" aria-label="Mission requirements"><span className="mp-brief-icon" aria-hidden="true">↳</span><div><h2>{mission.title}</h2><p>{mission.description}</p><details><summary>Read the three acceptance requirements</summary><ol>{mission.requirements.map(rule => <li key={rule}>{rule}</li>)}</ol></details></div><span className="mp-sandbox-label">Practice sandbox<br/><small>Browser simulation</small></span></section>
    <div className="mp-work-grid">
      <section className="mp-controls-panel" aria-labelledby="request-title">
        <div className="mp-panel-heading"><span className="mp-overline">01 / INVESTIGATE</span><span className="mp-panel-caption">Synthetic data</span></div>
        <h2 id="request-title">Send a request.</h2>
        <label className="mp-label" htmlFor="preview-case">Request scenario</label>
        <select id="preview-case" value={selected.id} onChange={event => dispatch({ type: 'select', caseId: event.target.value })}>{mission.cases.map(item => <option key={item.id} value={item.id}>{item.id} · {item.title}</option>)}</select>
        <div className="mp-request-bar"><span>PATCH</span><code>{selected.resource}</code></div>
        <dl className="mp-request-fields"><div><dt>Acting as</dt><dd><span className="mp-mini-avatar" aria-hidden="true">{selected.actor[0]}</span>{selected.actor}</dd></div><div><dt>Token</dt><dd>{selected.token === 'write' ? 'Valid · write scope' : selected.token === 'read' ? 'Valid · read only' : selected.token === 'expired' ? 'Expired' : 'Not supplied'}</dd></div><div><dt>Resource owner</dt><dd>{selected.owner}</dd></div><div><dt>Workspace role</dt><dd>{selected.role === 'outsider' ? 'Not a member' : selected.role === 'editor' ? 'Editor' : 'Viewer'}</dd></div></dl>
        <div className="mp-request-body"><span className="mp-overline">BODY</span><code>{'{ "title": "Updated title" }'}</code></div>
        <button className="mp-primary mp-full" onClick={() => dispatch({ type: 'run', suite: false })}>Run this request <span aria-hidden="true">→</span></button>
        <p className="mp-fine">Every run starts from a fresh synthetic resource.</p>
        <div className="mp-policy-section"><div className="mp-panel-heading"><span className="mp-overline">02 / REPAIR</span><span className="mp-panel-caption">Your policy</span></div><h2>Change the decision.</h2><PolicyEditor policy={work.policy} onChange={patch => dispatch({ type: 'policy', patch })}/></div>
      </section>
      <section className="mp-results-panel" aria-labelledby="response-title">
        <div className="mp-panel-heading"><span className="mp-overline">OBSERVE THE CONSEQUENCE</span><span className="mp-panel-caption">{selectedRun ? `Run ${String(selectedRun.sequence).padStart(2, '0')}` : 'Ready for your first run'}</span></div>
        <h2 id="response-title">What did the API do?</h2>
        <div className="mp-response-live" aria-live="polite" aria-atomic="true"><span className="mp-sr-only">{result ? `${selected.id}: observed ${result.status}, expected ${selected.expected}. ${result.passed ? 'Requirement met.' : 'Requirement not met.'}${stale ? ' This result is from an earlier policy.' : ''}` : 'Run the selected request to see its result.'}</span></div>
        {result ? <><Response item={selected} result={result} stale={stale}/><div className="mp-trace-heading"><h3>Follow the request.</h3><span>Identity → action → resource</span></div><ol className="mp-trace">{result.trace.map((step, index) => <li key={step.name} className={`is-${step.state}`}><span className="mp-trace-number" aria-hidden="true">{step.state === 'passed' ? '✓' : step.state === 'blocked' ? '×' : '–'}</span><div><div className="mp-trace-title"><strong>{step.name}</strong><small>{step.state === 'skipped' ? 'Not checked' : step.state === 'blocked' ? 'Stopped here' : 'Passed'}</small></div><p>{step.detail}</p></div><span className="mp-sr-only">Step {index + 1}</span></li>)}</ol></> : <div className="mp-response-empty"><span aria-hidden="true">↳</span><h3>Follow one request.<br/>Find the missing boundary.</h3><p>Select a scenario and run it. The response and trace will show how your current policy handled that person, token and resource.</p><div className="mp-empty-trace"><span>Identity</span><i>→</i><span>Scope</span><i>→</i><span>Resource</span></div></div>}
        <section className="mp-coach" aria-labelledby="coach-title"><div className="mp-coach-top"><span className="mp-overline">IN THE MARGIN</span><span>Authored guidance</span></div><h3 id="coach-title">{hintVisible ? coach.title : complete ? 'Ready for a different context?' : 'Need a smaller next step?'}</h3><p>{hintVisible ? coach.text : complete ? 'All six cases match the current ticket. The next mission changes the relationship that grants access.' : 'Use a focused hint or compare two requests. Keep making the changes yourself.'}</p>{missionId === 'teamboard' ? <p className="mp-help-disclosure">Hints and comparisons mark this transfer as assisted. Source cards remain available for open-reference practice.</p> : null}<div className="mp-coach-actions"><button className="mp-secondary" onClick={() => showHelp('hints')}>Give me a hint</button><button className="mp-text-button" onClick={() => showHelp('comparisons')}>Compare two requests ↔</button>{hintVisible ? <button className="mp-text-button" onClick={() => openSource(coach.source)}>Read the source ↗</button> : null}</div></section>
      </section>
    </div>
    {comparisonVisible ? <section className="mp-comparison" aria-label="Request comparison"><div className="mp-section-heading"><div><p className="mp-overline">A CONTROLLED COMPARISON</p><h2>{coach.title}</h2></div><button className="mp-text-button" onClick={closeComparison}>Close comparison ×</button></div><p>{coach.text}</p><div className="mp-comparison-grid">{coach.pair.map(id => { const item = mission.cases.find(entry => entry.id === id)!; const output = simulate(work.policy, item); return <article key={id}><span className="mp-overline">{item.id} / {item.title}</span><h3>{item.actor} <span aria-hidden="true">→</span> {item.owner}’s {mission.noun}</h3><p>{item.token === 'write' ? 'Valid write token' : item.token === 'read' ? 'Read-only token' : item.token === 'missing' ? 'No token' : 'Expired token'} · {item.role}</p><div className="mp-comparison-outcome"><strong>{output.status}</strong><span>{output.mutated ? 'Change written' : 'No change written'}</span></div><p className="mp-fine">{output.trace.at(-1)?.detail}</p></article>; })}</div><div className="mp-comparison-footer"><span>Explains your current policy. Comparison previews do not count as independent request runs.</span><button className="mp-text-button" onClick={() => openSource(coach.source)}>Read the supporting source ↗</button></div></section> : null}
    <section className="mp-suite" aria-labelledby="suite-title"><div className="mp-section-heading"><div><p className="mp-overline">03 / CHECK THE WHOLE BOUNDARY</p><h2 id="suite-title">Keep the right requests working.</h2></div><div className="mp-suite-control"><span>{suite ? `${suite.results.filter(item => item.passed).length}/6 in last check${suiteCurrent ? '' : ' · policy changed'}` : 'Six cases · not checked yet'}</span><button className="mp-primary" onClick={() => dispatch({ type: 'run', suite: true })}>{missionId === 'teamboard' ? 'Check this transfer' : 'Check all six cases'} <span aria-hidden="true">→</span></button></div></div><p className="mp-suite-description">A working policy permits legitimate edits and rejects the others. Select a case to inspect its request.</p><ul className="mp-case-list">{mission.cases.map(item => {
      const itemRun = currentResult(work, item.id);
      const output = itemRun?.results.find(row => row.caseId === item.id);
      const isCurrent = !!itemRun && samePolicy(itemRun.policy, work.policy);
      return <li key={item.id}><button className={`mp-case-row ${work.selectedCaseId === item.id ? 'is-selected' : ''}`} aria-pressed={work.selectedCaseId === item.id} onClick={() => dispatch({ type: 'select', caseId: item.id })}><span className="mp-case-id">{item.id}</span><span className="mp-case-name"><strong>{item.title}</strong><small>{item.detail}</small></span><span className={`mp-case-status ${output && isCurrent ? output.passed ? 'is-pass' : 'is-fail' : ''}`}>{!output ? 'Not run' : !isCurrent ? `${output.status} · earlier policy` : output.passed ? `${output.status} · requirement met` : `${output.status} · needs attention`}</span><span aria-hidden="true">↗</span></button></li>;
    })}</ul><div className="mp-suite-bottom"><span>{suiteCount} verification {suiteCount === 1 ? 'attempt' : 'attempts'} · {work.runs.filter(run => !run.suite).length} exploratory requests</span><span>{work.hints + work.comparisons ? 'Assistance requested' : 'No hints or comparisons requested'}</span></div></section>
    <div className="mp-work-bottom"><div><p className="mp-overline">{complete ? 'THE CURRENT POLICY PASSES ALL SIX CASES' : 'BEFORE MOVING ON'}</p><h3>{complete ? missionId === 'noteshare' ? 'Now change the context.' : 'Take the evidence with you.' : 'Check every requirement, including the allowed edits.'}</h3></div><button className="mp-primary" disabled={!complete} onClick={onNext}>{missionId === 'noteshare' ? 'Apply it elsewhere' : 'See my practice record'} <span aria-hidden="true">→</span></button></div>
    <div className="mp-source-shelf"><span className="mp-overline">KEEP A REFERENCE NEARBY</span><button className="mp-text-button" onClick={() => openSource('identity')}>Identity & HTTP status ↗</button><button className="mp-text-button" onClick={() => openSource('scope')}>Token scope ↗</button><button className="mp-text-button" onClick={() => openSource('resource')}>Resource permissions ↗</button></div>
  </>;
}

function PolicyEditor({ policy, onChange }: { policy: Policy; onChange: (patch: Partial<Policy>) => void }) {
  return <div className="mp-policy-editor"><fieldset className="mp-identity-field"><legend><span className="mp-control-index">01</span> When identity is invalid</legend><p className="mp-control-help">Choose the response for a missing or expired token.</p><div className="mp-radio-group">{([401, 403] as const).map(value => <label key={value} className={policy.identityStatus === value ? 'is-selected' : ''}><input type="radio" name="identity-status" value={value} checked={policy.identityStatus === value} onChange={() => onChange({ identityStatus: value })}/><span><strong>{value}</strong><small>{value === 401 ? 'Unauthorized' : 'Forbidden'}</small></span></label>)}</div></fieldset><div className="mp-policy-control"><label className="mp-toggle-row" htmlFor="write-scope"><span><span className="mp-control-index">02</span> Require write scope</span><input id="write-scope" type="checkbox" checked={policy.requireWriteScope} onChange={event => onChange({ requireWriteScope: event.target.checked })}/></label><p className="mp-control-help">Check whether this token permits an update.</p></div><div className="mp-policy-control"><label className="mp-label" htmlFor="resource-rule"><span className="mp-control-index">03</span> Who may change this resource?</label><select id="resource-rule" value={policy.resourceRule} onChange={event => onChange({ resourceRule: event.target.value as Policy['resourceRule'] })}><option value="none">Anyone with a valid identity</option><option value="owner">Only the resource owner</option><option value="workspace_editor">Editors in this workspace</option></select><p className="mp-control-help">Use the ticket’s business requirement.</p></div><div className="mp-policy-order"><span aria-hidden="true">↳</span> Evaluated in order: identity, scope, resource.</div></div>;
}

function Response({ item, result, stale }: { item: Case; result: Result; stale: boolean }) {
  return <div className="mp-response"><div className="mp-response-heading"><span className="mp-overline">{item.id} · OBSERVED RESPONSE</span><span className={stale ? 'mp-response-stale' : result.passed ? 'mp-response-match' : 'mp-response-mismatch'}>{stale ? 'Earlier policy' : result.passed ? 'Requirement met' : 'Requirement not met'}</span></div><div className="mp-status-code"><strong>{result.status}</strong><span>{result.status === 200 ? 'OK' : result.status === 401 ? 'Unauthorized' : 'Forbidden'}<small>Ticket expects {item.expected}</small></span></div><pre>{result.status === 401 ? 'WWW-Authenticate: Bearer\n\n' : ''}{JSON.stringify(result.mutated ? { id: item.resource.split('/').at(-1), title: 'Updated title', owner: item.owner } : { error: result.status === 401 ? 'authentication_required' : 'access_denied' }, null, 2)}</pre><div className="mp-mutation"><span aria-hidden="true">{result.mutated ? '↗' : '—'}</span><span>{result.mutated ? 'Resource changed: “Original title” → “Updated title”' : 'Resource unchanged: “Original title”'}</span></div>{stale ? <p className="mp-response-warning">You edited the policy after this run. Run the request again to see the new behavior.</p> : null}</div>;
}
